# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# Reference: https://docs.coderabbit.ai/reference/configuration
language: en-US
tone_instructions: "Review with a calm, practical tone and highlight blockers first."
reviews:
  profile: assertive
  high_level_summary: true
  high_level_summary_in_walkthrough: true
  path_filters:
    - "!dist/**"
    - "!node_modules/**"
    - "!coverage/**"
    - "src/**"
    - "lib/**"
    - "test/**"
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
  tools:
    eslint:
      enabled: true
    biome:
      enabled: true
    gitleaks:
      enabled: true
    actionlint:
      enabled: true
knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "docs/**"
      - "AGENTS.md"
      - "spec/**/*.md"
  learnings:
    scope: auto
  issues:
    scope: auto
  pull_requests:
    scope: auto
